---
name: 'Terraform CI'

on:  # yamllint disable-line rule:truthy
  pull_request:

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read

jobs:
  terraform:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 120
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::303467602807:role/tags-override-tester"
          role-session-name: "terraform-aws-service-network-ci"
          aws-region: "us-west-1"

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false

      # Prepare Python environment
      - name: Setup Python Environment
        run: |
          make bootstrap
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | sudo bash

      # Run all required linters
      - name: Code Style Check
        run: make lint

      # Generates an execution plan for Terraform
      - name: Terraform Tests
        run: make test
